name: sriov-operator-test
on: [pull_request]

jobs:
  virtual-k8s-cluster:
    name: k8s
    runs-on: [sriov]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: run test
        run: make test-e2e-conformance-virtual-k8s-cluster-ci

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifact
          path: ./artifacts.tar.gz

  virtual-ocp:
    name: ocp
    runs-on: [ ocp ]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: run test
        run: make test-e2e-conformance-virtual-ocp-cluster-ci

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: artifact
          path: ./artifacts.tar.gz
